### ISSUE TITLE
Remove skidmarks to enable custom Mods doesn't work

### ISSUE THREAD

**Issue by glocom** [GreepTheSheep/openplanet-skidmarks-manager#1]
The Delete skidmarks button doesn't work as intended. It does remove the custom skidmarks and the original skidmarks are shown in-game, but Custom Mods for a map don't function when you remove the custom skidmarks. To fix this issue, you have to remove (or rename) the ModWork entirely. It may not exists for Custom Mods to work.

**Comment by GreepTheSheep** [comment]
It's because of the ModWork folder that it's still there, I opened an issue to Openplanet to add a possibility to delete the folder https://github.com/openplanet-nl/issues/issues/92

The workaround (as you said) is to manually delete the ModWork folder in your `Documents/Trackmania/Skins/Stadium/`

**Comment by GreepTheSheep** [comment]
Fixed in commit 39bf7f649509515c6538cd82d64581d7681136c6 and 3b7d28f5cb41a87e75d93e0faed79d33464ccdae (forgot to link issue)
