### ISSUE TITLE
Script compilation failed

### ISSUE THREAD

**Issue by woutercools** [GreepTheSheep/openplanet-skidmarks-manager#2]
Skidmarks are displayed ingame but the manager window doesn't open.

![image](https://user-images.githubusercontent.com/16439116/167267385-4ffe01dc-f872-40e6-b818-a26bd83041db.png)

**Comment by GalahadIII** [comment]
I get the same error but since I just downloaded I can't set the skidmarks

![image](https://user-images.githubusercontent.com/89609656/167279086-69f6a843-86c1-4e7d-97ae-f8f25b6fadbe.png)

**Comment by GreepTheSheep** [comment]
Yeah, this error comes from Openplanet, you need at least Openplanet 1.23.5.
Actually, the default version is 1.23.3, you need to upgrade to the [beta version of Openplanet](https://openplanet.dev/download/next?branch=beta) as a workaround

**Comment by GreepTheSheep** [comment]
1.23.5 is out on default branch, closing issue
