### ISSUE TITLE
Plugin not showing in openplanet

### ISSUE THREAD

**Issue by HunterIsBetter** [GreepTheSheep/openplanet-skidmarks-manager#4]
Hi, I have the mod downloaded, but it isn't showing on openplanet so I was wondering if it was because I don't have standard or club access or openplanet glitching?
![image](https://user-images.githubusercontent.com/118878217/203484920-f4c76ecb-1b54-4806-90a1-48cdec9d0476.png)

**Comment by GreepTheSheep** [comment]
it's not in settings, it's on "Scripts" menu

**Comment by GreepTheSheep** [comment]
Closing this issue because of no new messages since 2 months
