### ISSUE TITLE
Custom skimarks not working; just thick black lines

### ISSUE THREAD

**Issue by msteinhoefel** [GreepTheSheep/openplanet-skidmarks-manager#8]
I installed the plugin, selected custom skids (for grass in this example) and reloaded the map. All I get is very thick, solidly black lines:

![2023-06-11 10_39_08-Trackmania](https://github.com/GreepTheSheep/openplanet-skidmarks-manager/assets/80283511/a4292d02-b51c-4e61-993a-7110647da9ee)

This happens regardless of which skids I choose. It also happens on dirt.

I've tried different maps (Spring 2023 - 02, TOTD June 9th and June 10th 2023), I have reloaded the maps and restarted the game multiple times. Nothing works.

I can successfully remove custom skids using the plugin UI and go back to default, but none of the custom skids work.

Edit: Also, the game and all plugins, including Maniaplanet itself, are fully up to date.

**Comment by GreepTheSheep** [comment]
Need to check on my side, maybe Nadeo does some update that broke custom skidmarks, idk at this point

**Comment by DjnxxD** [comment]
Same issue with me too

**Comment by GreepTheSheep** [comment]
@msteinhoefel @DjnxxD Can you please link logs when you apply skid marks ?
Openplanet>Logs

**Comment by msteinhoefel** [comment]
@GreepTheSheep 
This is the entire log of booting up the game, applying the "BlackBorder" skids to grass, launching Spring 2023-02 and driving it until I see the solid black lines on grass:

[Openplanet.log](https://github.com/GreepTheSheep/openplanet-skidmarks-manager/files/11731828/Openplanet.log)

**Comment by GreepTheSheep** [comment]
Hmm.. I have not much details about that. Can you try removing all skidmarks via "Advanced" tab, then relaunching the game, then reapply via "Advanced" tab ?

**Comment by msteinhoefel** [comment]
Same result. If the skids are applied - no matter if I do it for a specific surface or via Advanced tab - it's just thick, black lines.

**Comment by GreepTheSheep** [comment]
Can you try deleting the ModWork folder ? It's located in Documents\TrackMania\Skins\Stadium\ModWork. Then restart the game to see

**Comment by msteinhoefel** [comment]
I think I have an idea what's going wrong here. I looked into that folder and CarGrassMarks.dds is 0 KB. Manually downloaded from the github repo, the file should be 129 KB.

I manually replaced that file and now it works. So I suspect that the plugin either can't properly download the file from the repo, or maybe it's having trouble properly writing the file to my disk...?
